#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 5437bdb3-d237-461a-9fdd-fee7c45dfa8a
# Source File: C:\Users\MarkLocal\Documents\SAPIEN\PowerShell Studio\Projects\O365DynamicListViewer\Dynamic Distribution List Members.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
GgIAAB+LCAAAAAAABACNktFKwzAUhu8He4fQ+y6r26xCmgtXJ4LTMYe3ctqcSiRNSpKKe3tT20mH
IF5+yTnfT37C9liaD7THHDzw6YQQtrPmHUv/DQFf0DppNE9mCaMnGO42UuF9zlfLRVqIYhGLi0Ua
Ly8TiK8rIeIKMS2XK1HBFTA6DA+rQ8rh2CCfMzrGk9woEeIIHae5AQYke6zQoi7xEWrMoojctFKJ
LJpH/NmD9W0za5zrw/9eXYNS8Rak3hhbvzauGrtO50FW/Vt2p0wBKqiSkYqsTV2DFrefHnXXZRYd
bIsR76ddSEjOEnro3/3TU09PVr5JDaob6HJ5ftRQy5Lk0nkri9YHP3kIQLZYF6HMYG+CgdFfq9MJ
o2d/4QuNWhJhGgIAAA==#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.2.129
     Generated on:       10/22/2016 4:37 AM
     Generated by:       Mark Kraus
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2016
#>


#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
ZAMAAB+LCAAAAAAABAC9k99Lw0AMx98F/4djz+Xa2tU6uBZkshdBxYn6mnbpOLwfI7lz9L93mzJF
HwSRkpd8E5IPIYm6x86/Ig1XEEDsHNbe1ZMzmU+a0xMh1C3ptXZgFtrgDVhslgEoxI3cMKv0R/ZQ
c8mMtjUa+aA/I0NjufNkdJuIxw/WVGZ7S8Q8mhAJa4cxEJhE3MVdj+4ahwf/gq5uqwrKrjzPZ8UU
s4uZSo9dv1OWAwe0YzDkk3Yrv2W58GR5FOJ+U+OACLbarf/Cyoq+7Ks+z1dlBgX8znq2ZpSZ5p7w
/0FH+X7yKv36Vc0baArZVmQDAAA=#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
    $CurExecPolicy = Get-ExecutionPolicy
    if ($CurExecPolicy -like 'Restricted') {
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
    }
    
	if((Call-MainForm_psf) -eq 'OK')
	{
        Remove-PSSession $Global:o365Session
	}
	
	$global:ExitCode = 0 #Set the exit code for the Packager
}







#endregion Source: Startup.pss

#region Source: MainForm.psf
function Call-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
2a8AAB+LCAAAAAAABADtXVmTosq2fjfC/2D0072Hjk4RmW7s3RE4a2mJY2m97HAARREUAYc4P/6u
BAdKUUGt6u5zrzt2d6Nk5sq1vjXmQv+qSwPdloxNpmf2YvCPpaJrf39L/CC//YxGYrG/qoYyUrSe
mlNU6bU3k35WeoqW043Zj/lS/gudfewO6k+kgRkzN3Pp72+NzdKUZj/eFG2or5Y/8Fj3z+8xv4++
x9o7KpI/4vi/77G0pZqWIf2tSZZp9NTvMdHqq8rgRdo09amk/d1n2R49oBmSp5JSnOO/xTQg5e9v
e1K/xQZjRR0acOu3tK6Zhq4u3e0BraKhzyXD3OzGCJapNwY9VcooM0nDdMCtzPcYSf2F9rfeGlrR
h9K3nzlY6eaYtKpImtlQtjAgySW+x2iKvDmoONC1Pf3waQoEYGx+CoKQEoSWkIU/BSErFIWUjv/Z
HuFPRl3n87QgKMJUEMrJLFyPivjWmjASXkY1+DifgXsrGUGIRtwZ0noJ3mfHSWH3cmZY1eDN0jue
QXfXglf6+Pnuld3/A8/28YXELYcQ/C8i+H+Lzq5tCq7hJSKKgGvK6jCIQBsCISIaQfYWfwZ3UPzF
GZxr53N47a6Jsk7YhGrJfdTubNdo8/oWjbAyn+pLCMnvMC2rlXiEdFa2r81osMhGFmckEfXW4hDH
vANhpfbEAtq27QmLOP1NYpGQmRhoJdAM4vK1qo26xc4GoQl9mFHGuxRJAhHcBk2Q0UcUYl4o3ias
lSijaGTz2qQRj2aEjbY80KT0mvHdjEIV3hQysoHi4zUnogRxoJElYAWJho8qibKFyDrHySgfjcRh
DZdvCN9BIHnHx+Rmxoswo4RntDHNSQbxxYGdQbw92XOBwHx3JLGm65hvnPBaNdDgvbDdrenhE5Yd
UZnbTZhRwzOyDs3AhUahvEKonzzKmuWAbzyrEjYntSwKRvQNRKXrHHLX9EjCkeXkpX/ChQnmwmbP
BZjthA8FtWzCiATsajWVRWfND7K9woVo5AofGg4XLBsNSsG4EI1c40NYLsBOr/DhChfWU1s80yGY
7S408HWHC5KBmoXmCnGTFiGjOUaIjQjbdvkgE9WF2LmNhqNOdAy7g2pvlI1WfAFmE7lKvbpFL+QW
MG2lOJloGjDje3GygRmZ6zrhtS0O3lBhC0orbO0JGtDw9kbtsTaXOcywKnJ7Gl2a3wXgwmgslxEh
ah9m3OPNeYc/aJXLWZUBFi762wQiFwInc+pblXV3RSX6YJLojSwjpkqx+xmd2S5Yn2AW0msf8Wye
GVanljjc69yS716OH8jjPzJnfqB0ebabuwzOBQe9+32f6mH4FU745r1DPqzpyJquGgxiFI63eUIT
m8hYZqidzaaJHRYczSIO6LiLJmdPCMsWdAGVWcSyFULkN1iTHZ1YtYg9YlPgTNCm1Abf1pbFAlJf
tiTith3QyzUvfvRt1/DGHvwnb8vg6Nh3QiYKOtiz6gyUezVPg1YKr1hnJthSrHOOnhZr0ha0xjAO
1glrURPuWKcKrMgjzCeXj7675vE1wNjxC5iTxMyy+6ir9zdoO1TBv8a7BAvWprNCiU2Vs4kytrGL
PpVAXLMOXKkM5cze/7J7ywDode0ZBZqsYE0GaVzy8TZn22jO2gnEzHjwyOTadpiXRPx2CpOBr+ew
fXNswZFPR/zxw5FdOKPBY1GVsX2k4BRvzoxDWjTQS9uw0JZcsIhoLFAHUVKT2dF4EU0Yb2B3RX4w
koPT4EOB4zeikZ3noJwZpL3VLsfB2lxBtD8F0cg9NOwoYPZoek00bWzvopF7aLhEgWNDbtFAH2no
2Dub60vB3r49RxLRyD00XKJgF4fcL4kPFMBO76DhEgUw2x00XKLAa98el4Sjp3ehwY8CJ367Wy9P
KYhG7kWDHwXRyL1o8KPg1L49JgmspzdoQGWIIXc22dfTHCnAfuEuNHgi68zBPoJ9AwuZJ+EdOj3n
IfOKQ4xJE1uI8CBS+OAnsBW/zgWsp9docPzAioN8dPROxdGGlCCKzYuHKDaLLWa1bm1ROUfh/JRU
EUTOr3PwJPaSSro5Md+VQ/gq37j3GBsRfQOid8MGf/mWLKzRel2D/CBdtWw3p9n7EbhOx8Ul2gzf
gWbIxJtVah81nNJww2Ofc8XBm8NpQjYgr+rLELnUFjijSLAQudB59pDjHLJ0waXRPotbYLZgkcvt
+A1hvnFyE4KYggiRCqlCPlpuUxC/ddGz47cr124Ue4hJacmGKHYGs12LY8NGsX7+NFg07xfL384X
npLL3PU6zvaC/3Cyn5T7Bq6v7V5Z4cJLfIhvN64P9RB+n7cH0yL/6zvxdjvPOs2rMCJ5ewL4I3kU
DH+fwzcvQtk9DY7NXVXYJKIauAZodiwWFdoFE8XncU4kijpqohWfSeISCPaGTlTzufnpsaLnVhkb
lKihyYscR/HUkt35gV0FxmPvdnHIwVM4VUM3r3KsOFXFGYecfIBvvtXYAq7GTi1xV41dj6vgJ1Ku
TT76CfCnhxrMmV9g9hmJa8Vb2II61TPNaCZ2krrNt1Mr7egIQyDIsfsFHvFzBZVRkeyDj6/gqlDK
8V1TcYn9wlwEqq0O5KN1CrKixFuRs3l6JoqokCscc5YjzX6+jZhBFr+rvwVDg1P1iZtbGhcgeJnv
YA8uzgwbxdUtJ/J6NKKAz1ZemnHESCwPBG/RBCWqBQacswWIdLXK8dhoSyBu03Vq1r58/pAvAKcp
ps8hjywv5fHyjo90fsHLbuV9bZaTOK93suglB96MR5OP6HA1HR2tFfVhRlbMsGibG0PU4Mj+kNef
Ub33p/LcLYkFkD3OsyDrLpIdE23GPdbm4yrIcsUXkm5dMkwNZxeHOLusvBWsj9VaX5qTDhrQvjp7
1b6dVYwPkYyI9bhJTVaIyGAPTlzLT0/jt+0K0LC+hgY/LOzqb5f5clY391SYMc01XN3d8H0auac8
t3XAFw1+fPXkWSHRcJZf7OpIxq6WBWmGrcFUbCA0+GHhQz0kFBr8sBCNHNHgkR3Yq2xWXiLOfoMY
Ep2cJ1yMEHFefx8a/LDwAW/X0MA4aCCOaAgUhwRGgx8WAvkFXzT4YSFIHOKPBj++HuxbaDT4YQHw
dica/LBwVkcKjAY/LGB/eh8a/LCAa9H3oeEW3sKhIUj8FhwNfli4gbcraPDDQoBzmRB+Ym/fwqPB
DwsO3u5Cgx8WfOtvd/uJQ508NBr8sBCNPCtqOMFbSDT40XiCtweiBrceci8anEjHwYJMn5wDXjtd
CuEnjuf14aMGpyaYPI1D8Ckd35BsXNWhSGcDIpoxkE06lSpv/cOph1y2DBfj3uB+wpEctSYQD7RN
5LKbwa6KBx3Y1eOS+6wn0+os0cYcQFzsZBwK04kjdluGPSgMxM3OedjuXOZ6RhHGT5ziDd+h4Vpq
JwlrTpktieJ1mxNdNJxnuJpxkISF+YZzN7Rpd2AXoiRmkFQCSOzxZYXzE2HqIccaIGfjCqBYI0Se
Um1sHhDIdigc8XZeCfXs4pYv88a9h/wyRHZ5wZ+69stBpINYo4woRCbSnMwNWhK1OwU+cvoajW4c
4tlVDletHQtKM3HIV4PFJQHz+mN26akH1916MFpBeuepB2vHeohHEk7FeNu1WNQvshvEWASPcOuI
sctfL9P4jD4Hdm8ZQLNwBXhlZpKI6r1xiLNuVZ6u1Z0C5VmBr/3ikB3n93m8czqAG36Ab7J8tHcf
8/xn8e3xuqVjg1m36vgg37gA1eNnvJ40W9opW6/c2brOW7gndP9p7cKwzEN6+jje7r/+LfD2mXzb
WQL2eH76f4lvRxvqnKFteY1G4HzB6SSDnm/9gXg7nqnRBNhYErwrol8WvMxn+yiDcllj6XfSCPGb
7J5xePjmW0X8LfXUt0dvhnv0+iPYpVuZL+7jkGO0ddKt9voCPp/vWciNENlOHnz+hIHo/tDXenKi
9uvt2/EE47RLMBpx+wSP58wXTtv9T1kOpzDjFHBFj0beIO7odMtrRG82EK85p00c6rD37PpRvnk6
FSEaw+cLmR5EeC9zuemeiqzInDfCC7Dr8/qb/x2H0yenY7jThDjYOQlyKDiPYp9p3z70OeBPnWo/
MTbtPmpRNj5Te3XO1KxDnwPjmxVVj+eAWbwr53mF9LS8DMOnD9dOnpVqbg3ENrP87apPKPtGcYeY
EVsnYgtxLqSxSEa97naDNvUO7HrXy91ZHDpO9noNCHb6VNsNyBZL6sRCW3rBIv5dRgU0pPtgMHoW
LxMJPOP4JRM/dINfy7Mu8iXVRJgLuaBcuGrfXN/k2GSn/zKPn+pwnl1xnzwp41OUVDwD1qtdhj0u
QE8JFne9rBBJZDmZ53FlQCuXE4idFIGmWsLWwEJCPo0KeEaGQB+8Jbwot7cWuHCt3nv92o8L99g3
m8Xks+DBrcqEQtSmB+ncro+rm5Q3KJke8qKrA/Zgm0R8UwI9dEbwYp/dzYCOXfKeDMStuPjrqUO1
0xF8Aw3Xz0/DosHPo+NzmeaCsPmpIpbRdGGTkEyNYHLnVNjN0j11pGPu56Lndh/X5eubXLh6nhVa
J674BW8dE2yuY6226zmL3G5w8pWld1UidwX3POs5cciubnkvGvy4cPP89CIafKq5Tt+ga/cLuYzp
aj6xXtmyW/l8Vhxyl06c+9NHdGKnp2d8OI1sDnVMpztyUMpsd5bg8TjkIheu+4WwXAigpze54NVT
/NxGuwNRAn6g8Rl51kMW0ssFmO1BC+nlwu68/ko91+k/CsiFm/FbKC5c9qf36MRpf0hwNPhx4aH8
9IwLwfxCUC6E0NMAXPjYHxIGDTfjt4d1wuXbM6KG0/6Qx3UisD8NxIUbeVZILlyph9yhE0/J6w9c
wHh7TtSAbp2fhtYJHz19QCd8+Xa3Tnz0p4/qBMz2oIUM5RdCcSF4nhWEC7f6Q8JxIRp51EJ6ueDG
vc+KpKORZ0UNmAvX+0PCcuGqnobWCX9/eq9OeOvkj+vE3XmWLxdu+4UwXAiopwG5cDyvf4ZOHPj2
lEga19+eEzVgLkQjz4oaAsdvgbnw6fW3B3Ti4XrvBy780vrbDS6c6OmDOvGb19+eFDXc9AuhdeLr
6m/hdQLj7TlRA/pt62/GtfjtTp34T6i/nXBBo9Z3+4XAXPi962+H7z9ye6Lccxfvs08hTtt/r/qb
pzJfdetv109c063yEm1oicXn83IBTRiNRCyqEiKaOqftzresuCcaOz21L/b3/j71N6ffTV4SiM8P
xIx7Kne7g9PzfQ5CE+NnncXn7fi03TnTTfYUXiSSG1FGFNFhEOpTaN+FcDzp+X3qb8frOf5GsGWl
TKFEPs/Z3KhFgI5st66e3uoaPXnW0+FTqWZtUVHtmChuxjkRdz03gW/OGrw2JnYnYovy9lfX37x8
83RkOn6gl4Tl1AVLovhww4lcvVE96WIOGPd+7BBOTfEpMFlnZT6H8VfXCiu0yv7a+tvlaw+Cnecs
ne/NkGhti/v0oxHW5oq16gfph5Hlhx6WcH7hE+pvAfnm6XNwbMnEJBBhr2QZf5fkGq35Jv5mDfHI
lbNnje/PF27gzcJ8eKy7416+eXq5bdzLjfWcaEcjhtxBdQowvs4V7+31ucG3kL0+N+O3u64v8c37
dEGHBfIahOg+iV7JZ5ynC446cLXee0Fr9p1f1/q+fn3/24n/9XR0RiPOt/AwrMAjXh7jPkDnea2z
p10CdQECQq70Ad7lF76Kb/LHntBENcMgurHkZYhT5POe0GjE8/0zD/eE/oZ90YeoFfPN2dXG7RA2
cIcw/p6CwB3Cz7Bvvw3fDv3it7rF/8C+6F+Ptyt8u/ykyLXXb/kUyf/P9vBs6VIrSxcyNb3nPpJD
lhrZekPYf8FUTSgK+Ht989byLec8lbNtZdetOvZEotbdyi/ZDrEuZKtLiGoEMUU1UUObyNqEqtKt
olit9ZEsGPLbVpNouYzsFSs2BrLFGyKaVOw+LdcbU5i0Xmq06ql2YdJjh/HSYFFZRSPZYnucrxXf
lHWBEglq1GiXpGkqnn1TjQ1aJWuzOGcbdUZcMMVWsVur1Uaj8TiVSr9X6y2yzb9KcZZ/HZdVqrqw
IcInFKuJyFlyNtRti26+chUtJ+V6qNPJs/MmM2l1SoZsGORre9WQKUKwpDlhdJVmtfW2arP8sNNs
50glO+TfqGhknaonRJkeyq1lXTGmkkn25enoxapz8uKNeVdemSExHonvLUSS6iQ+3zBqUhcXb0UL
xtUZy160ivk2TLGYA23K23T7Uix3mAWEENnZXEOpoaA25ayRlYurhoHv5hZsobWW4oRlFYnxZBzX
6bWGklqX0AsonoRowRCBbj0aeZkWyHotP10YydqoCFSv0jXTXsyF91JH3CSEUVXXUqVUHbVrQnex
kFPTVI2vV4TNy5zoC6k12eXKxXKGydZy02ikPeHeRq+TxXqVLXYK8UmeyAzG8jq5jW+2Lb2YKk+r
ScaUX9mk3O+OCsyL2cwwhEFMqcS7UMkvDMbWMttsTtAbC7BI5uQdqXy5kE13mbk9JztosakViy2b
QitEqykhm12ItJmoLAtcjuXXiaxdWKZsfihnOpONYCclKoOWotAZ8SDTDCckxcSqvDZHK1awc4nM
ZJnmmqt8oauu5FG1ui0L5mjNVpapREZbblaFFWH7P1v2u+up+5IKU/ndHk9HZZ1FwiAxWPVXMhrR
Qq1Go8JKmE3SBW01E7RpcSiPu0KzjjZMr5VJZWiOqcFfJBePRkZ5NlNg6dEov6hyqLYROk2DlfgF
vRrVOFkAWa3rcGevlksMuxOCLxVTa6XAJvVRegaAnRHdSkqtgmgZIhWNLHpdYqFXBsJLyxohjZ/1
eu/jifbCJmvTUbqjNYYI9fLV2XDEsNmRnnnLlDq8XDEm+V6PnqY648xGKLVeJ3IjZ8JOR+uXaS1T
NuIvRodlJCqenefymdKiZ8s2w8i1xrTTzWpyvzChR8nXxmsltamw/clak9ZDUnhJkeMNazQzMyor
QWwpFlNkhWgwpaY52hbLo+JAjTdUlOHmFeG1vmh06lspE9e5Va5GKp36S/89Nau/CZIxnVat9rhV
7ea5Al0aVgzQer2yEmt5spu1KjNRz/SsdOMtU01vSqnui57bdNYCrFZKqstmWkAtU6nUMotEqdRN
FQXGVuqzDJMB1VLZyuKdiEa4nMWVu7N+azvMzNP8pp+lKqV2jhoQRsFs9KtTc5IlRqyo6XUpq7Xa
tGz2x+uS1WjWTWXBrcFSCKV+3iImTTka6ZqjdztuK9VqG+JLeW2maxZJkm91RNRW8P6L2GAGnJIq
tQvxoSTVOi1LYa26PFzR606q9FpsyWj6Qpb1JbuMRixNLI6V1npL2NWiRLyty8YLUZ5vlQJZKpTt
9ASC1m3cUuwC6o453mw0tks8ZtiaLt+HFccOp9P5bDZbzkJmVOdbxQ7BjDcv/bbzLfGpUr1FZ41p
aTQa/f33X2j3MyO7nyS59Rsl+Mdgvh1+LObm7Q2zZ5iivlRMBf+2SVrSTMloDAxJ0m6ObUpr89vP
zAaulEEsoyxNQ+lbeKJYGS5iFWnWl4zl+TxZG5bZTVLWe8Mjvf/gy7+Qc8P+7ts/apOyTFPXPv1n
bWCHA13TgJi+s+C1n7c551ZW6/VVCfaa66lL6Ywp5wPK+qDnSoVPfo9R57+Dc0n4p3QGGOj+EA5L
f48lgqzT7PWL2lBaf/uZiAe53QXKgawAQ1pLqa0srZ7aMDeqlOoNpmld1Y1vP5uG5cs8L6bSIM3p
OR/+cd4/QRdy4fXbgS3tUp66A2lH4JBUKOB8WPMzUUPygVGT/lLIfODAc/BS7vUl9dPhouJVxN5y
udKNYTi4OD+f5UjyEqMu44vDlokLDLAPVAYGGO3/M2BXARaEJhdge3L+59xPhZY1njGlrz9d2nua
d+uFlLc2GDtqoc+/x8qSbH6P1ZXROIiKHSWfSIJQKDqw5E8oDjBuPyI97gGx/wqMlkQCjF4wt3SE
C/sE4X+holdlWRlIFEMLw5migeEztN6XKT3PgTomwum8H8GBJUomE+ENABPYALi0xYC4mENdzCVv
Jv1JFgHTjPn9iy1CEL/uwuKE4BDqnQyv3ud2Krwk8Q915g1l2Fak1aeLsy4tYSReLqQkVVVfYdY2
dWE4rANpwfMNz9iMpEqmFHK4F0QpHQKoWVgwQbxmzbSC1BsCHwsSHoWF7v6s595iBZ7Hwya4pQji
CireHSbdaT5P1h7ygMC6JEsgZbBE7iZyirE0HV2JIe9GEN7JH72zcu8/dGPZWU9Rr+4qXHTNg9tj
k4FN6tFoBBhSBy2rauomcAAA1mCnmZBlKX1VCm4adj+zm8SJIhNkP0fTfe5QwlvuhtkzrWWqZ3x+
0m4ZBv5ZYWfBe5N2WJ+OB3ekH9YMFFdrkhrONh4Y6Iz9Vdq1dKjo94w5poJ8VM8aY32150VAFfD8
XHQiSAB8hPF5OhoexnlDt+ZfEUuO8EJ9fU3+gigSV6yYILG7C/4DqcGlR7PfY1w46QWtbjVMfR7c
Kl4pnzuidorofvP8NjVKt6ya1ucbTKrr0q8h5gZmLqHljlr6VYjhAkHSD2OXUHa+z0CDXcDx5IXy
6FXE+XnJyyXS+cY9cQlMWthaqX+19JwvfiXTM1v3e0I4p6gmzn1gB2BResafAOVEIn43lE/3GwLS
ZIK/B9MBBxwx7ZIYM/XYnki/yPbz0X3Kqj8U5Tji2Z3J/gngpmj6LnB7thnGTF86xboKab844hKk
MV0Xz8Q/G8YepjwPvWl91te/IiLdBUnYyzwG3eth6fngDFxm9JXmSACCtd3lhcjsKQqAedczTUUb
HQZflvdF5cFHZn455CXV8XI4hNYkk7ga6xd9X1Mbv2OjE/A2JBXAB1tJj3vaSAKkzRTTxMzwUvrP
pdtO0X2hQcA71Z9p0yFJNqTl+HHN+KqIhbzLpnu3GcaoM/cY9YBwdoz6jrBYcMqeadW9bAkE4D+g
6pB4oOpw37GDNzUEs0kHr7geaA5RfuC+x6hkoP6X69ng59cfLscqv6kVfDC43aPnq+JbClsn7m5j
GD7GJclPD3L39vBXxbkfefPHOXWcbQZp+bsNYmwCw8eM4eB4pDYMCDnqDhCSYZyyUzwQVHWPwl9V
QTjy588Doir1jCBtzs80p97CFq6achcSBX8wHikOg8Y4LmUFrLYe0ejXf3IRjZiwmHs4+5UG0cOQ
58HvC5vc0o12dj3XDTOnqHcfLIQ2hzcb425YUCpU2n2+0RDYxYbUty3uKnRDVWEb7ZhLGq7F+jTE
3Qeir2qKM2EdiM6fhZ8wpgzDKK3P5riPyu1falijkbQ0hflc0oI5Ie8cDd0yBrjlAvbici0kNHkW
YzOMd/dwL4xBZdkL/XnXUHnhfq9Vw6BxqzzDD7T94/ngD3KwrmFOGTD3w+C8y8PiLgaKDOb5vNmH
S3IIRDCJe+K9EFbKpejHjx9fnm24K/9xwZ1r0p+TZ3zZYRATFq7eXX52zdC3H/4SXnceFScljfYX
YtbLkPDVwo8XAQ6HxtJg+hVevgFh7mBczgjiNSxfgxZ4LJ+I3h9Vx9VuDthnGEnfDONKweX2vQ6O
MBExl56bI8IgKKykm7qufkV3pQnr9HvG1ba0Swd4gmE43ey+CnO1FzMoMPbU3YbFWF9hljWVeVCC
drVjBh+eBEDHAUmnZiysZL+q8XNH+GmH54X9Caoy0mZgt7799Pc+l3O6xtxQtNHNASndGErG7tC3
3lOW0nnE7o+Cky0E1OTjk8oBFnpThuYYo+G0OhJWur+gf35/xn14tuGGxHaPfqhqWlJVn28SOBnm
Nqi7PHXW8O+I8xfdgaib99/onb8gsLOm0z9HXocnNj5PXHiJMNLak/RZwnrUdP46YblPoQSSFOTP
aigpOXMHlFCwe6+KJyzTq3NJwzWBjNJT9dGncxoo1WRYbugsd9FfOZEwJiu7dto0LiRAZ6GLJPeA
sCzm+2Bp37zf7VJ0i3Z4tdh//YBh//3vf+G//o2PQ/C7S7g+f5jaL0YpSOo8gFSE5VKaAbuk5X6u
3TubnzPwaoaq9J/A8r/QYdbTVVwhf8UaTwfS7RWxGfmahYzeCkKje9aKUzItszJJDul4j+rdXqsz
U79kT2ndkJ6/0OHShfxfqC4NdFsyNlhWP/8XUHFpo9mvAAA=#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$MainForm = New-Object 'System.Windows.Forms.Form'
	$Disconnectbutton = New-Object 'System.Windows.Forms.Button'
	$ConnectButton = New-Object 'System.Windows.Forms.Button'
	$labelPassword = New-Object 'System.Windows.Forms.Label'
	$PasswordTextBox = New-Object 'System.Windows.Forms.TextBox'
	$labelOffice365AdminUserna = New-Object 'System.Windows.Forms.Label'
	$UserNameTextBox = New-Object 'System.Windows.Forms.TextBox'
	$ResultGrid = New-Object 'System.Windows.Forms.DataGridView'
	$CurrentStatus = New-Object 'System.Windows.Forms.StatusBar'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonCopyListName = New-Object 'System.Windows.Forms.Button'
	$buttonCopyFilterToClipboar = New-Object 'System.Windows.Forms.Button'
	$buttonShowMembers = New-Object 'System.Windows.Forms.Button'
	$DynamicLists = New-Object 'System.Windows.Forms.ComboBox'
	$buttonRefreshLists = New-Object 'System.Windows.Forms.Button'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$buttonRefreshMembers = New-Object 'System.Windows.Forms.Button'
	$CopyButton = New-Object 'System.Windows.Forms.Button'
	$Clearbutton = New-Object 'System.Windows.Forms.Button'
	$labelCSVExportFile = New-Object 'System.Windows.Forms.Label'
	$textboxFile = New-Object 'System.Windows.Forms.TextBox'
	$buttonBrowse = New-Object 'System.Windows.Forms.Button'
	$ExportButton = New-Object 'System.Windows.Forms.Button'
	$SearchLDAP = New-Object 'System.Windows.Forms.CheckBox'
	$toolbar1 = New-Object 'System.Windows.Forms.ToolBar'
	$statusbarpanel1 = New-Object 'System.Windows.Forms.StatusBarPanel'
	$FirstName = New-Object 'System.Windows.Forms.DataGridViewTextBoxColumn'
	$LastName = New-Object 'System.Windows.Forms.DataGridViewTextBoxColumn'
	$Email = New-Object 'System.Windows.Forms.DataGridViewTextBoxColumn'
	$openfiledialog1 = New-Object 'System.Windows.Forms.OpenFileDialog'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$MainForm_Load={
	    If ($Global:o365Session) {
	        $statusbarpanel1.Text = 'Connected'
	    }
	    else {
	        $statusbarpanel1.Text = 'Disconnected'
	    }
	}
	
	
	
	
	#region Control Helper Functions
	function Load-DataGridView
	{
		<#
		.SYNOPSIS
			This functions helps you load items into a DataGridView.
	
		.DESCRIPTION
			Use this function to dynamically load items into the DataGridView control.
	
		.PARAMETER  DataGridView
			The DataGridView control you want to add items to.
	
		.PARAMETER  Item
			The object or objects you wish to load into the DataGridView's items collection.
		
		.PARAMETER  DataMember
			Sets the name of the list or table in the data source for which the DataGridView is displaying data.
	
		.PARAMETER AutoSizeColumns
		    Resizes DataGridView control's columns after loading the items.
		#>
		Param (
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			[System.Windows.Forms.DataGridView]$DataGridView,
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			$Item,
		    [Parameter(Mandatory=$false)]
			[string]$DataMember,
			[System.Windows.Forms.DataGridViewAutoSizeColumnMode]$AutoSizeColumns = 'None'
		)
		$DataGridView.SuspendLayout()
		$DataGridView.DataMember = $DataMember
		
		if ($Item -is [System.Data.DataSet] -and $Item.Tables.Count -gt 0)
		{
			$DataGridView.DataSource = $Item.Tables[0]
		}
		elseif ($Item -is [System.ComponentModel.IListSource]`
		-or $Item -is [System.ComponentModel.IBindingList] -or $Item -is [System.ComponentModel.IBindingListView] )
		{
			$DataGridView.DataSource = $Item
		}
		else
		{
			$array = New-Object System.Collections.ArrayList
			
			if ($Item -is [System.Collections.IList])
			{
				$array.AddRange($Item)
			}
			else
			{
				$array.Add($Item)
			}
			$DataGridView.DataSource = $array
		}
		
		if ($AutoSizeColumns -ne 'None')
		{
			$DataGridView.AutoResizeColumns($AutoSizeColumns)
		}
		
		$DataGridView.ResumeLayout()
	}
	
	function ConvertTo-DataTable
	{
		<#
			.SYNOPSIS
				Converts objects into a DataTable.
		
			.DESCRIPTION
				Converts objects into a DataTable, which are used for DataBinding.
		
			.PARAMETER  InputObject
				The input to convert into a DataTable.
		
			.PARAMETER  Table
				The DataTable you wish to load the input into.
		
			.PARAMETER RetainColumns
				This switch tells the function to keep the DataTable's existing columns.
			
			.PARAMETER FilterWMIProperties
				This switch removes WMI properties that start with an underline.
		
			.EXAMPLE
				$DataTable = ConvertTo-DataTable -InputObject (Get-Process)
		#>
		[OutputType([System.Data.DataTable])]
		param(
		[ValidateNotNull()]
		$InputObject, 
		[ValidateNotNull()]
		[System.Data.DataTable]$Table,
		[switch]$RetainColumns,
		[switch]$FilterWMIProperties)
		
		if($null -eq $Table)
		{
			$Table = New-Object System.Data.DataTable
		}
		
		if ($InputObject -is [System.Data.DataTable])
		{
			$Table = $InputObject
		}
		elseif ($InputObject -is [System.Data.DataSet] -and $InputObject.Tables.Count -gt 0)
		{
			$Table = $InputObject.Tables[0]
		}
		else
		{
			if (-not $RetainColumns -or $Table.Columns.Count -eq 0)
			{
				#Clear out the Table Contents
				$Table.Clear()
				
				if ($null -eq $InputObject) { return } #Empty Data
				
				$object = $null
				#find the first non null value
				foreach ($item in $InputObject)
				{
					if ($null -ne $item)
					{
						$object = $item
						break
					}
				}
				
				if ($null -eq $object) { return } #All null then empty
				
				#Get all the properties in order to create the columns
				foreach ($prop in $object.PSObject.Get_Properties())
				{
					if (-not $FilterWMIProperties -or -not $prop.Name.StartsWith('__')) #filter out WMI properties
					{
						#Get the type from the Definition string
						$type = $null
						
						if ($null -ne $prop.Value)
						{
							try { $type = $prop.Value.GetType() }
							catch { }
						}
						
						if ($null -ne $type) # -and [System.Type]::GetTypeCode($type) -ne 'Object')
						{
							[void]$table.Columns.Add($prop.Name, $type)
						}
						else #Type info not found
						{
							[void]$table.Columns.Add($prop.Name)
						}
					}
				}
				
				if ($object -is [System.Data.DataRow])
				{
					foreach ($item in $InputObject)
					{
						$Table.Rows.Add($item)
					}
					return @( ,$Table)
				}
			}
			else
			{
				$Table.Rows.Clear()
			}
			
			foreach ($item in $InputObject)
			{
				$row = $table.NewRow()
				
				if ($item)
				{
					foreach ($prop in $item.PSObject.Get_Properties())
					{
						if ($table.Columns.Contains($prop.Name))
						{
							$row.Item($prop.Name) = $prop.Value
						}
					}
				}
				[void]$table.Rows.Add($row)
			}
		}
		
		return @(,$Table)	
	}
	
	function Sort-ListViewColumn 
	{
		<#
		.SYNOPSIS
			Sort the ListView's item using the specified column.
	
		.DESCRIPTION
			Sort the ListView's item using the specified column.
			This function uses Add-Type to define a class that sort the items.
			The ListView's Tag property is used to keep track of the sorting.
	
		.PARAMETER ListView
			The ListView control to sort.
	
		.PARAMETER ColumnIndex
			The index of the column to use for sorting.
			
		.PARAMETER  SortOrder
			The direction to sort the items. If not specified or set to None, it will toggle.
		
		.EXAMPLE
			Sort-ListViewColumn -ListView $listview1 -ColumnIndex 0
	#>
		param(	
				[ValidateNotNull()]
				[Parameter(Mandatory=$true)]
				[System.Windows.Forms.ListView]$ListView,
				[Parameter(Mandatory=$true)]
				[int]$ColumnIndex,
				[System.Windows.Forms.SortOrder]$SortOrder = 'None')
		
		if(($ListView.Items.Count -eq 0) -or ($ColumnIndex -lt 0) -or ($ColumnIndex -ge $ListView.Columns.Count))
		{
			return;
		}
		
		#region Define ListViewItemComparer
			try{
			$local:type = [ListViewItemComparer]
		}
		catch{
		Add-Type -ReferencedAssemblies ('System.Windows.Forms') -TypeDefinition  @" 
	using System;
	using System.Windows.Forms;
	using System.Collections;
	public class ListViewItemComparer : IComparer
	{
	    public int column;
	    public SortOrder sortOrder;
	    public ListViewItemComparer()
	    {
	        column = 0;
			sortOrder = SortOrder.Ascending;
	    }
	    public ListViewItemComparer(int column, SortOrder sort)
	    {
	        this.column = column;
			sortOrder = sort;
	    }
	    public int Compare(object x, object y)
	    {
			if(column >= ((ListViewItem)x).SubItems.Count)
				return  sortOrder == SortOrder.Ascending ? -1 : 1;
		
			if(column >= ((ListViewItem)y).SubItems.Count)
				return sortOrder == SortOrder.Ascending ? 1 : -1;
		
			if(sortOrder == SortOrder.Ascending)
	        	return String.Compare(((ListViewItem)x).SubItems[column].Text, ((ListViewItem)y).SubItems[column].Text);
			else
				return String.Compare(((ListViewItem)y).SubItems[column].Text, ((ListViewItem)x).SubItems[column].Text);
	    }
	}
"@  | Out-Null
		}
		#endregion
		
		if($ListView.Tag -is [ListViewItemComparer])
		{
			#Toggle the Sort Order
			if($SortOrder -eq [System.Windows.Forms.SortOrder]::None)
			{
				if($ListView.Tag.column -eq $ColumnIndex -and $ListView.Tag.sortOrder -eq 'Ascending')
				{
					$ListView.Tag.sortOrder = 'Descending'
				}
				else
				{
					$ListView.Tag.sortOrder = 'Ascending'
				}
			}
			else
			{
				$ListView.Tag.sortOrder = $SortOrder
			}
			
			$ListView.Tag.column = $ColumnIndex
			$ListView.Sort()#Sort the items
		}
		else
		{
			if($SortOrder -eq [System.Windows.Forms.SortOrder]::None)
			{
				$SortOrder = [System.Windows.Forms.SortOrder]::Ascending	
			}
			
			#Set to Tag because for some reason in PowerShell ListViewItemSorter prop returns null
			$ListView.Tag = New-Object ListViewItemComparer ($ColumnIndex, $SortOrder) 
			$ListView.ListViewItemSorter = $ListView.Tag #Automatically sorts
		}
	}
	
	
	function Add-ListViewItem
	{
	<#
		.SYNOPSIS
			Adds the item(s) to the ListView and stores the object in the ListViewItem's Tag property.
	
		.DESCRIPTION
			Adds the item(s) to the ListView and stores the object in the ListViewItem's Tag property.
	
		.PARAMETER ListView
			The ListView control to add the items to.
	
		.PARAMETER Items
			The object or objects you wish to load into the ListView's Items collection.
			
		.PARAMETER  ImageIndex
			The index of a predefined image in the ListView's ImageList.
		
		.PARAMETER  SubItems
			List of strings to add as Subitems.
		
		.PARAMETER Group
			The group to place the item(s) in.
		
		.PARAMETER Clear
			This switch clears the ListView's Items before adding the new item(s).
		
		.EXAMPLE
			Add-ListViewItem -ListView $listview1 -Items "Test" -Group $listview1.Groups[0] -ImageIndex 0 -SubItems "Installed"
	#>
		
		Param( 
		[ValidateNotNull()]
		[Parameter(Mandatory=$true)]
		[System.Windows.Forms.ListView]$ListView,
		[ValidateNotNull()]
		[Parameter(Mandatory=$true)]
		$Items,
		[int]$ImageIndex = -1,
		[string[]]$SubItems,
		$Group,
		[switch]$Clear)
		
		if($Clear)
		{
			$ListView.Items.Clear();
	    }
	    
	    $lvGroup = $null
	    if ($Group -is [System.Windows.Forms.ListViewGroup])
	    {
	        $lvGroup = $Group
	    }
	    elseif ($Group -is [string])
	    {
	        #$lvGroup = $ListView.Group[$Group] # Case sensitive
	        foreach ($groupItem in $ListView.Groups)
	        {
	            if ($groupItem.Name -eq $Group)
	            {
	                $lvGroup = $groupItem
	                break
	            }
	        }
	        
	        if ($null -eq $lvGroup)
	        {
	            $lvGroup = $ListView.Groups.Add($Group, $Group)
	        }
	    }
	    
		if($Items -is [Array])
		{
			$ListView.BeginUpdate()
			foreach ($item in $Items)
			{		
				$listitem  = $ListView.Items.Add($item.ToString(), $ImageIndex)
				#Store the object in the Tag
				$listitem.Tag = $item
				
				if($null -ne $SubItems)
				{
					$listitem.SubItems.AddRange($SubItems)
				}
				
				if($null -ne $lvGroup)
				{
					$listitem.Group = $lvGroup
				}
			}
			$ListView.EndUpdate()
		}
		else
		{
			#Add a new item to the ListView
			$listitem  = $ListView.Items.Add($Items.ToString(), $ImageIndex)
			#Store the object in the Tag
			$listitem.Tag = $Items
			
			if($null -ne $SubItems)
			{
				$listitem.SubItems.AddRange($SubItems)
			}
			
			if($null -ne $lvGroup)
			{
				$listitem.Group = $lvGroup
			}
		}
	}
	
	
	function Load-ComboBox 
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ComboBox.
	
		.DESCRIPTION
			Use this function to dynamically load items into the ComboBox control.
	
		.PARAMETER  ComboBox
			The ComboBox control you want to add items to.
	
		.PARAMETER  Items
			The object or objects you wish to load into the ComboBox's Items collection.
	
		.PARAMETER  DisplayMember
			Indicates the property to display for the items in this control.
		
		.PARAMETER  Append
			Adds the item(s) to the ComboBox without clearing the Items collection.
		
		.EXAMPLE
			Load-ComboBox $combobox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Load-ComboBox $combobox1 "Red" -Append
			Load-ComboBox $combobox1 "White" -Append
			Load-ComboBox $combobox1 "Blue" -Append
		
		.EXAMPLE
			Load-ComboBox $combobox1 (Get-Process) "ProcessName"
	#>
		Param (
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			[System.Windows.Forms.ComboBox]$ComboBox,
			[ValidateNotNull()]
			[Parameter(Mandatory=$true)]
			$Items,
		    [Parameter(Mandatory=$false)]
			[string]$DisplayMember,
			[switch]$Append
		)
		
		if(-not $Append)
		{
			$ComboBox.Items.Clear()	
		}
		
		if($Items -is [Object[]])
		{
			$ComboBox.Items.AddRange($Items)
		}
		elseif ($Items -is [System.Collections.IEnumerable])
		{
			$ComboBox.BeginUpdate()
			foreach($obj in $Items)
			{
				$ComboBox.Items.Add($obj)	
			}
			$ComboBox.EndUpdate()
		}
		else
		{
			$ComboBox.Items.Add($Items)	
		}
	
		$ComboBox.DisplayMember = $DisplayMember	
	}
	#endregion
	
	
	$DynamicLists_Click={
	    If ($Global:DynListPopulated) { return }
	    try {
	        $MainForm.Cursor = 'WaitCursor'
	        $statusbarpanel1.Text = 'Updating Dynamic lists...'
	        try {
	            $DynamicListResults = Get-O365DynamicDistributionGroup -ErrorAction 'Stop' | Sort-Object -Property Name
	            foreach ($DynamicListResult in $DynamicListResults) {
	                Load-ComboBox $DynamicLists $DynamicListResult.Name -Append
	            }            
	            $Global:DynListPopulated = $true
	            $statusbarpanel1.Text = 'Ready'
	        }
	        Catch {
	            $statusbarpanel1.Text = 'Error: Unable to load list. Reconnect with MGR Credentials.'
	            $DynamicLists.Enabled = $false
	        }
	        $MainForm.Cursor = 'Default'
	    }
	    catch {
	        exit
	    }
	    
	}
	
	$Clearbutton_Click={
	    $statusbarpanel1.Text = 'Clearing Results...'
	    $MainForm.Cursor = 'WaitCursor'
	    $ResultGrid.Rows.Clear()
	    $Global:DynListMembers = $null
	    $MainForm.Cursor = 'Default'
	    if ($Global:o365Session) {
	        $statusbarpanel1.Text = 'Ready'
	    }
	    else {
	        $statusbarpanel1.Text = 'Disconnected'
	    }
	    $MainForm.Cursor = 'Default'
	}
	
	$CopyButton_Click = {
	    $ResultGrid.ClipboardCopyMode = 'EnableAlwaysIncludeHeaderText'
	    $ResultGrid.SelectAll()
	    $Contents = $ResultGrid.GetClipboardContent()
	    if ($Contents) {
	        [System.Windows.Forms.Clipboard]::SetDataObject($Contents)
	    }
	    $ResultGrid.ClipboardCopyMode = 'EnableWithAutoHeaderText'
	    $statusbarpanel1.Text = 'All Results Copied to Clipboard'
	}
	
	$buttonBrowse_Click={
	    $ExportButton.Enabled = $False
		if($openfiledialog1.ShowDialog() -eq 'OK')
		{
			$textboxFile.Text = $openfiledialog1.FileName
	    }
	    else {
	        return
	    }
	    try {
	        $FilePath = Split-Path -Path $textboxFile.Text -Parent -ErrorAction Stop
	        If (-not (Test-Path $FilePath)) {
	            throw
	        }
	        $ExportButton.Enabled = $true
	    }
	    Catch {
	        [void][System.Windows.Forms.MessageBox]::Show("There is a problem with the file you selected or the folder does not exist. Please select a different file.", "CSV File Error")
	        return
	    }
	    
	}
	
	$ExportButton_Click = {
	    $PreviousStatus = $statusbarpanel1.Text
	    $statusbarpanel1.Text = 'Exporting to CSV...'
	    $MainForm.Cursor = 'WaitCursor'
	    try {
	        $FilePath = Split-Path -Path $textboxFile.Text -Parent -ErrorAction Stop
	        If (-not (Test-Path $FilePath)) {
	            throw
	        }
	    }
	    Catch {
	        [void][System.Windows.Forms.MessageBox]::Show("There is a problem with the file you selected or the folder does not exist. Please select a different file.", "CSV File Error")
	        $ExportButton.Enabled = $false
	        $statusbarpanel1.Text = $PreviousStatus
	        return
	    }
	    try {
	        $Global:DynListMembers |
	            Select-Object -property * -ExcludeProperty 'PSComputerName', 'RunspaceId', 'PSShowComputerName'|
	                Export-Csv -Path $textboxFile.Text -ErrorAction Stop -NoTypeInformation
	    }
	    Catch {
	        [void][System.Windows.Forms.MessageBox]::Show("There was a problem expotiing the file.", "CSV Export Error")
	    }
	    [void][System.Windows.Forms.MessageBox]::Show("Successfully exported to '$($textboxFile.Text)''", "CSV Export Successful.")
	    $statusbarpanel1.Text = $PreviousStatus
	    $MainForm.Cursor = 'Default'
	}
	
	$textboxFile_TextChanged = {
	    $ExportButton.Enabled = $false
	    try {
	        $FilePath = Split-Path -Path $textboxFile.Text -Parent -ErrorAction Stop
	        If (-not (Test-Path $FilePath)) {
	            throw
	        }
	        $ExportButton.Enabled = $true
	    }
	    Catch {
	        return
	    }    
	}
	
	
	
	$ConnectButton_Click = {
	    $statusbarpanel1.Text = 'Connecting to Office 365...'
	    $MainForm.Cursor = 'WaitCursor'
	    $DynamicLists.Enabled = $false
	    $buttonCopyFilterToClipboar.Enabled = $false
	    try {
	        Remove-PSSession $Global:o365Session -ErrorAction Stop
	    }
	    Catch {
	        <# noop #>
	    }
	    $SecurePasword = $PasswordTextBox.Text | ConvertTo-SecureString -AsPlainText -Force
	    $PasswordTextBox.Text = ''
	    $Global:Credential = New-Object System.Management.Automation.PSCredential ($UserNameTextBox.Text, $SecurePasword)
	    Connect-O365
	    try {
	        Get-O365DynamicDistributionGroup -resultsize 1 -erroraction 'stop' | Out-Null
	        $Disconnectbutton.Enabled = $true
	        $DynamicLists.Enabled = $true
	        $buttonRefreshLists.Enabled = $true
	        $statusbarpanel1.Text = 'Connected'
	    }
	    catch {
	        [void][System.Windows.Forms.MessageBox]::Show("Office 365 Connection Failed. Please try again with a correct username and password", "Office 365 Connection Failed")
	        try {
	            Remove-PSSession $Global:o365Session -ErrorAction Stop
	        }
	        Catch {
	        <# noop #>
	        }
	        $DynamicLists.Enabled = $false
	        $buttonRefreshLists.Enabled = $false
	        $buttonShowMembers.Enabled = $false
	        $buttonCopyListName.Enabled = $false
	        $buttonCopyFilterToClipboar.Enabled = $false
	        $statusbarpanel1.Text = 'Disconnected'
	    }
	    $MainForm.Cursor = 'Default'
	}
	
	$Disconnectbutton_Click={
	    $MainForm.Cursor = 'WaitCursor'
	    $statusbarpanel1.Text = 'Disconnecting from Office 365...'
	    try {
	        Remove-PSSession $Global:o365Session -ErrorAction Stop
	    }
	    Catch {
	        <# noop #>
	    }
	    $Global:o365Session = $null
	    $Disconnectbutton.Enabled = $false
	    $DynamicLists.Enabled = $false
	    $buttonRefreshLists.Enabled = $false
	    $buttonShowMembers.Enabled = $false
	    $buttonCopyListName.Enabled = $false
	    $buttonCopyFilterToClipboar.Enabled = $false
	    $buttonRefreshMembers.Enabled = $False
	    $MainForm.Cursor = 'Default'
	    $statusbarpanel1.Text = 'Disconnected'
	}
	
	$buttonRefreshLists_Click={
	    try {
	        $MainForm.Cursor = 'WaitCursor'
	        $statusbarpanel1.Text = 'Updating Dynamic lists...'
	        $DynamicLists.Items.Clear()
	        try {
	            $DynamicListResults = Get-O365DynamicDistributionGroup -ErrorAction 'Stop' | Sort-Object -Property Name
	            foreach ($DynamicListResult in $DynamicListResults) {
	                Load-ComboBox $DynamicLists $DynamicListResult.Name -Append
	            }
	            $Global:DynListPopulated = $true
	            $statusbarpanel1.Text = 'Ready'
	        }
	        Catch {
	            $statusbarpanel1.Text = 'Error: Unable to load list. Reconnect with MGR Credentials.'
	            $DynamicLists.Enabled = $false
	        }
	        $MainForm.Cursor = 'Default'
	    }
	    catch {
	        exit
	    }    
	}
	
	$buttonRefreshMembers_Click={
	    if (-not $Global:o365Session -or -not $DynamicLists.GetItemText($DynamicLists.SelectedItem) ) { return }
	    $MainForm.Cursor = 'WaitCursor'
	    $statusbarpanel1.Text = "Loading Members for '{0}'..." -f $DynamicLists.GetItemText($DynamicLists.SelectedItem)
	    $ResultGrid.Rows.Clear()
	    $Param = @{
	        Identity = $DynamicLists.GetItemText($DynamicLists.SelectedItem)
	        ErrorAction = 'SilentlyContinue'
	    }
	    $Filter = (Get-O365DynamicDistributionGroup @Param).RecipientFilter
	    $Global:DynListMembers = @()
	    Get-O365Recipient -Filter $Filter -ResultSize unlimited | ForEach-Object {
	        $CurMember = $_
	        $Global:DynListMembers += $CurMember
	        $ResultGrid.Rows.Add($CurMember.FirstName, $CurMember.LastName, $CurMember.PrimarySmtpAddress)
	    }
	    $MainForm.Cursor = 'Default'
	    $ResultGrid.Cursor = 'Default'
	    $statusbarpanel1.Text = "Displaying Members for '{0}'. Ready." -f $DynamicLists.GetItemText($DynamicLists.SelectedItem)
	}
	
	$buttonShowMembers_Click={
	    if (-not $Global:o365Session) { return }
	    $MainForm.Cursor = 'WaitCursor'
	    $statusbarpanel1.Text = "Loading Members for '{0}'..." -f $DynamicLists.GetItemText($DynamicLists.SelectedItem)
	    $ResultGrid.Rows.Clear()
	    $Param = @{
	        Identity = $DynamicLists.GetItemText($DynamicLists.SelectedItem)
	        ErrorAction = 'SilentlyContinue'
	    }
	    $Filter = (Get-O365DynamicDistributionGroup @Param).RecipientFilter
	    $Global:DynListMembers = @()
	    Get-O365Recipient -Filter $Filter -ResultSize unlimited | ForEach-Object {
	        $CurMember = $_
	        $Global:DynListMembers += $CurMember
	        $ResultGrid.Rows.Add($CurMember.FirstName, $CurMember.LastName, $CurMember.PrimarySmtpAddress)
	    }
	    $buttonRefreshMembers.Enabled = $true
	    $MainForm.Cursor = 'Default'
	    $ResultGrid.Cursor = 'Default'
	    $statusbarpanel1.Text = "Displaying Members for '{0}'. Ready." -f $DynamicLists.GetItemText($DynamicLists.SelectedItem)	
	}
	
	$DynamicLists_SelectionChangeCommitted={
	    $buttonShowMembers.Enabled = $true
	    $buttonCopyListName.Enabled = $true
	    $buttonCopyFilterToClipboar.Enabled = $true
	}
	
	$buttonCopyFilterToClipboar_Click = {
	    if (-not $Global:o365Session -or -not $DynamicLists.GetItemText($DynamicLists.SelectedItem)) { return }
	    $MainForm.Cursor = 'WaitCursor'
	    $PreviousStatus = $statusbarpanel1.Text
	    $statusbarpanel1.Text = "Loading Filter for '{0}'" -f $DynamicLists.GetItemText($DynamicLists.SelectedItem)
	    $Filter = (Get-O365DynamicDistributionGroup @Param).RecipientFilter
	    $MainForm.Cursor = 'Default'
	    $statusbarpanel1.Text = $PreviousStatus
	    [System.Windows.Forms.Clipboard]::SetText($Filter)
	}
	
	$buttonCopyListName_Click={
	    [System.Windows.Forms.Clipboard]::SetText($DynamicLists.GetItemText($DynamicLists.SelectedItem))
	}
	
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$MainForm.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_PasswordTextBox = $PasswordTextBox.Text
		$script:MainForm_UserNameTextBox = $UserNameTextBox.Text
		$script:MainForm_ResultGrid = $ResultGrid.SelectedCells
		$script:MainForm_DynamicLists = $DynamicLists.Text
		$script:MainForm_DynamicLists_SelectedItem = $DynamicLists.SelectedItem
		$script:MainForm_textboxFile = $textboxFile.Text
		$script:MainForm_SearchLDAP = $SearchLDAP.Checked
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$Disconnectbutton.remove_Click($Disconnectbutton_Click)
			$ConnectButton.remove_Click($ConnectButton_Click)
			$buttonCopyListName.remove_Click($buttonCopyListName_Click)
			$buttonCopyFilterToClipboar.remove_Click($buttonCopyFilterToClipboar_Click)
			$buttonShowMembers.remove_Click($buttonShowMembers_Click)
			$DynamicLists.remove_SelectionChangeCommitted($DynamicLists_SelectionChangeCommitted)
			$DynamicLists.remove_Click($DynamicLists_Click)
			$buttonRefreshLists.remove_Click($buttonRefreshLists_Click)
			$buttonRefreshMembers.remove_Click($buttonRefreshMembers_Click)
			$CopyButton.remove_Click($CopyButton_Click)
			$Clearbutton.remove_Click($Clearbutton_Click)
			$textboxFile.remove_TextChanged($textboxFile_TextChanged)
			$buttonBrowse.remove_Click($buttonBrowse_Click)
			$ExportButton.remove_Click($ExportButton_Click)
			$MainForm.remove_Load($MainForm_Load)
			$MainForm.remove_Load($Form_StateCorrection_Load)
			$MainForm.remove_Closing($Form_StoreValues_Closing)
			$MainForm.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$MainForm.SuspendLayout()
	$groupbox1.SuspendLayout()
	$groupbox2.SuspendLayout()
	$statusbarpanel1.BeginInit()
	#
	# MainForm
	#
	$MainForm.Controls.Add($Disconnectbutton)
	$MainForm.Controls.Add($ConnectButton)
	$MainForm.Controls.Add($labelPassword)
	$MainForm.Controls.Add($PasswordTextBox)
	$MainForm.Controls.Add($labelOffice365AdminUserna)
	$MainForm.Controls.Add($UserNameTextBox)
	$MainForm.Controls.Add($ResultGrid)
	$MainForm.Controls.Add($CurrentStatus)
	$MainForm.Controls.Add($groupbox1)
	$MainForm.Controls.Add($groupbox2)
	$MainForm.AutoScaleDimensions = '6, 13'
	$MainForm.AutoScaleMode = 'Font'
	$MainForm.ClientSize = '482, 531'
	#region Binary Data
	$MainForm.Icon = [System.Convert]::FromBase64String('
AAABAAUAEBAAAAEAIABoBAAAVgAAABgYAAABACAAiAkAAL4EAAAgIAAAAQAgAKgQAABGDgAAMDAA
AAEAIACoJQAA7h4AAAAAAAABACAAwQQAAJZEAAAoAAAAEAAAACAAAAABACAAAAAAAAAEAAAAAAAA
AAAAAAAAAAAAAAAA/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/////P/3+Pz/3uX6/+/y+//+
/vz////8//39/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//39/P////z//Pz8/+Lo+v+lufb/VXzx/yNW
7f9Bbe//fZvz/7nJ9//o7fv//Pz8//z8/P/8/Pz//Pz8//39/P/r7/v/u8r4/3WU8/86Z+//JVju
/zVj7/8oWe7/ADjr/wA56/8GQOv/YIXy//j5/P/8/Pz//f38//P1+/+8y/j/rb/3/6K39v+uwPf/
yNT5/9/m+v/z9fv/iaT0/wA56/8AO+v/ADfr/0hx8P/2+Pz//Pz8//7+/P/e5fr/M2Lu/1R88f/G
0/j////8///+/P/+/fz////8/4ym9P8AOev/ADvr/wA46/9IcvD/9vj8//z8/P/+/vz/3uX6/x5R
7f8ANOr/cZHz//7+/P/8/Pz//Pz8/////P+MpvT/ADnr/wA76/8AOOv/SHLw//b4/P/8/Pz//v78
/97l+v8eUu3/ADbr/3CR8//+/vz//Pz8//z8/P////z/jKb0/wA56/8AO+v/ADjr/0hy8P/2+Pz/
/Pz8//7+/P/e5fr/HlLt/wA26/9wkfP//v78//z8/P/8/Pz////8/4ym9P8AOev/ADvr/wA46/9I
cvD/9vj8//z8/P/+/vz/3uX6/x5S7f8ANuv/cJHz//7+/P/8/Pz//Pz8/////P+MpvT/ADnr/wA7
6/8AOOv/SHLw//b4/P/8/Pz//v78/97l+v8eUu3/ADbr/3CR8//+/vz//Pz8//z8/P////z/jKb0
/wA56/8AO+v/ADjr/0hy8P/2+Pz//Pz8//7+/P/e5fr/HlLt/wA26/9xkvP////8//39/P/8/Pz/
///8/4ym9P8AOev/ADvr/wA46/9IcvD/9vj8//z8/P/+/vz/3uX6/x9R7f8ANer/THTw/8jU+f/p
7fv/+vv8/////f+OqPX/ADnr/wA76/8AOOv/SHLw//b4/P/8/Pz//f38//P1+/+XrvX/QW3v/w9H
7P8MROz/K1zu/1uB8f+TrPX/ZIjy/wA66/8AO+v/ADfr/0hx8P/2+Pz//Pz8//z8/P/8/Pz//v78
//Hz+//Azvj/c5Pz/yla7v8DO+v/ADfr/wI86/8AOOv/ADnr/wZA6/9ghfL/+Pn8//z8/P/8/Pz/
/Pz8//z8/P/9/fz////8//39/P/l6vr/qbz2/1qA8f8lWO7/QW3v/32b8/+5yff/6O37//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/////P/3+Pz/3uX6/+/y+//+/vz////8//39
/P/8/Pz//Pz8/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAoAAAAGAAAADAAAAABACAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAA
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/////P//
//z////8//7+/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//f38/////P/9/fz/5Or6/6i89v9+nPT/rsD3/9/m+v/5+fz////8
///+/P/9/fz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//7+/P///vz/
7/L7/77M+P9ykvP/K1zu/wU+6/8AOOv/Bj/r/yJV7f9VfPH/lKz1/8zX+f/x9Pv//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//79/P////z/9vf8/87Z+f+HovT/Omfv/wpC7P8AN+v/Ajvr/wxF
7P8IQez/ADrr/wA56/8AOOv/ATvr/xBH7P9/nPT//f38//z8/P/8/Pz//Pz8//z8/P/9/Pz/+/v8
/9/m+v+muvb/Yoby/zdl7/80Y+7/THXw/2yO8v+LpvT/qb32/8TR+P9MdfD/ADjr/wA76/8AO+v/
ADvr/wA36/9ihfL//fz8//z8/P/8/Pz//Pz8//39/P/v8vv/p7v2/6m99v+1xvf/x9P4/9zk+v/u
8fv/+Pn8//79/P////z////8//7+/P9dgvH/ADjr/wA76/8AO+v/ADvr/wA46/9ihvL//fz8//z8
/P/8/Pz//Pz8//79/P/d5Pr/KVru/z1q7/+Sq/X/3eT6//39/P/9/fz//Pz8//z8/P/8/Pz//Pz8
//v8/P9cgfH/ADjr/wA76/8AO+v/ADvr/wA46/9ihvL//fz8//z8/P/8/Pz//Pz8//79/P/e5fr/
HlLt/wA36/8AOev/SHLw//L0+//9/fz//Pz8//z8/P/8/Pz//Pz8//v8/P9cgfH/ADjr/wA76/8A
O+v/ADvr/wA46/9ihvL//fz8//z8/P/8/Pz//Pz8//79/P/e5fr/HlLt/wA66/8AOOv/N2Tv/+/y
+//9/fz//Pz8//z8/P/8/Pz//Pz8//v8/P9cgfH/ADjr/wA76/8AO+v/ADvr/wA46/9ihvL//fz8
//z8/P/8/Pz//Pz8//79/P/e5fr/HlLt/wA56/8AOOv/N2Xv/+/y+//9/fz//Pz8//z8/P/8/Pz/
/Pz8//v8/P9cgfH/ADjr/wA76/8AO+v/ADvr/wA46/9ihvL//fz8//z8/P/8/Pz//Pz8//79/P/e
5fr/HlLt/wA56/8AOOv/N2Xv/+/y+//9/fz//Pz8//z8/P/8/Pz//Pz8//v8/P9cgfH/ADjr/wA7
6/8AO+v/ADvr/wA46/9ihvL//fz8//z8/P/8/Pz//Pz8//79/P/e5fr/HlLt/wA56/8AOOv/N2Xv
/+/y+//9/fz//Pz8//z8/P/8/Pz//Pz8//v8/P9cgfH/ADjr/wA76/8AO+v/ADvr/wA46/9ihvL/
/fz8//z8/P/8/Pz//Pz8//79/P/e5fr/HlLt/wA56/8AOOv/N2Xv/+/y+//9/fz//Pz8//z8/P/8
/Pz//Pz8//v8/P9cgfH/ADjr/wA76/8AO+v/ADvr/wA46/9ihvL//fz8//z8/P/8/Pz//Pz8//79
/P/e5fr/HlLt/wA56/8AOOv/N2Xv/+/y+//9/fz//Pz8//z8/P/8/Pz//Pz8//v8/P9cgfH/ADjr
/wA76/8AO+v/ADvr/wA46/9ihvL//fz8//z8/P/8/Pz//Pz8//79/P/e5fr/HlLt/wA56/8AOOv/
N2Xv/+/y+//9/fz//Pz8//z8/P/8/Pz//Pz8//v8/P9cgfH/ADjr/wA76/8AO+v/ADvr/wA46/9i
hvL//fz8//z8/P/8/Pz//Pz8//79/P/e5fr/HlLt/wA56/8AOOv/N2Xv/+/y+//9/fz//Pz8//z8
/P/8/Pz//Pz8//v8/P9cgfH/ADjr/wA76/8AO+v/ADvr/wA46/9ihvL//fz8//z8/P/8/Pz//Pz8
//79/P/e5fr/HlLt/wA56/8AOOv/N2Xv//L1+/////z//f38//z8/P/8/Pz//Pz8//v8/P9cgfH/
ADjr/wA76/8AO+v/ADvr/wA46/9ihvL//fz8//z8/P/8/Pz//Pz8//7+/P/e5fr/HlDt/wA36/8A
Oev/G1Dt/5Cp9f/G0vj/5+z7//r6/P////z////8//39/P9cgfH/ADjr/wA76/8AO+v/ADvr/wA4
6/9ihvL//fz8//z8/P/8/Pz//Pz8//39/P/w8/v/gZ30/y1e7v8GP+v/ADfr/wE66/8ORuz/LF3u
/1l/8f+Np/X/vs34/+Lo+v9YfvH/ADjr/wA76/8AO+v/ADvr/wA46/9ihvL//fz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//f38/+br+/+rvvf/W4Hx/xxQ7f8COuv/ADbr/wA36/8AOuv/C0Ps/ydZ7v8W
TO3/ADrr/wA76/8AO+v/ADvr/wA36/9ihfL//fz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//39
/P////z/+fr8/9bf+f+QqvX/Q27v/w5G7P8AOev/ADjr/wA56/8AOuv/ADvr/wA56/8AOOv/ATvr
/xBH7P9/nPT//f38//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//7+/P////z/
8fT7/8HP+P91lfP/LV3u/wY/6/8AOOv/Bj/r/yJV7f9VfPH/lKz1/8zX+f/x9Pv//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//f38///+/P/9/fz/5ev6/6m8
9v9+nPT/rsD3/9/m+v/5+fz////8///+/P/9/fz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/////P////z////8//7+/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAKAAAACAAAABAAAAAAQAgAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAPz8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//79/P/+/vz//fz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//f38/////P/9/fz/5ev6/9vj+v/19/z////8///+/P/9/fz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//v78///+/P/w8/v/wM74/3SU8/8tXu7/HVHt/0p08P+Io/T/w9D4/+vv+//9
/fz////8//7+/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/+/fz////8//j5/P/S3Pn/jKf0/0Bs7/8ORuz/ADnr/wA56/8AOuv/ADjr
/wA66/8ORuz/M2Lu/2yO8v+rvvf/3OT6//f4/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//39/P////z//Pz8/+Ho+v+kuPb/VXzx/xhO7f8BOev/ADbr/wA36/8A
OOv/ADnr/wA76/8AO+v/ADvr/wA66/8AOev/ADjr/wU/6/8eUu3/nrT2///+/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//7+/P/+/vz/6+/7/7bH9/9pi/L/I1bt/wM86/8BOuv/CkPs
/xpP7f8uX+7/R3Lw/2WI8v95mPP/HFHt/wA66/8AO+v/ADvr/wA76/8AO+v/ADvr/wA36/9+mvP/
///8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/3+Pz/0tz5/5Or9f9XfvH/Pmrv/0lz8P9o
ivL/iKT0/6e79v/Cz/j/2OH6/+ru+//19/z//f38/+/z+/8yYe7/ADnr/wA76/8AO+v/ADvr/wA7
6/8AO+v/ADjr/36b8/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/9/fz/6+/7/5Gq9f+lufb/xtL4
/9zk+v/s8Pv/9/j8//39/P////z////8/////P/+/vz//f38//z8/P/9/fz/7PD7/zFh7v8AOev/
ADvr/wA76/8AO+v/ADvr/wA76/8AOOv/fpvz/////P/8/Pz//Pz8//z8/P/8/Pz//Pz8//7+/P/e
5Pr/I1Xt/yha7v90lPP/w9H4//P1+//9/fz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//39
/P/s8Pv/MWHu/wA56/8AO+v/ADvr/wA76/8AO+v/ADvr/wA46/9+m/P////8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//v78/97l+v8eUu3/ADjr/wA56/8PRuz/T3jw/+Dm+v/+/fz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//f38/+zw+/8xYe7/ADnr/wA76/8AO+v/ADvr/wA76/8AO+v/ADjr/36b8///
//z//Pz8//z8/P/8/Pz//Pz8//z8/P/+/vz/3uX6/x5S7f8AOev/ADvr/wA56/8QROz/y9b5///+
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/9/fz/7PD7/zFh7v8AOev/ADvr/wA76/8AO+v/ADvr
/wA76/8AOOv/fpvz/////P/8/Pz//Pz8//z8/P/8/Pz//Pz8//7+/P/e5fr/HlLt/wA56/8AO+v/
ADrr/xBH7P/L1vn///78//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//39/P/s8Pv/MWHu/wA56/8A
O+v/ADvr/wA76/8AO+v/ADvr/wA46/9+m/P////8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v78/97l
+v8eUu3/ADnr/wA76/8AOuv/EEfs/8vW+f///vz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//f38
/+zw+/8xYe7/ADnr/wA76/8AO+v/ADvr/wA76/8AO+v/ADjr/36b8/////z//Pz8//z8/P/8/Pz/
/Pz8//z8/P/+/vz/3uX6/x5S7f8AOev/ADvr/wA66/8QR+z/y9b5///+/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/9/fz/7PD7/zFh7v8AOev/ADvr/wA76/8AO+v/ADvr/wA76/8AOOv/fpvz////
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//7+/P/e5fr/HlLt/wA56/8AO+v/ADrr/xBH7P/L1vn///78
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//39/P/s8Pv/MWHu/wA56/8AO+v/ADvr/wA76/8AO+v/
ADvr/wA46/9+m/P////8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v78/97l+v8eUu3/ADnr/wA76/8A
Ouv/EEfs/8vW+f///vz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//f38/+zw+/8xYe7/ADnr/wA7
6/8AO+v/ADvr/wA76/8AO+v/ADjr/36b8/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/+/vz/3uX6
/x5S7f8AOev/ADvr/wA66/8QR+z/y9b5///+/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/9/fz/
7PD7/zFh7v8AOev/ADvr/wA76/8AO+v/ADvr/wA76/8AOOv/fpvz/////P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//7+/P/e5fr/HlLt/wA56/8AO+v/ADrr/xBH7P/L1vn///78//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//39/P/s8Pv/MWHu/wA56/8AO+v/ADvr/wA76/8AO+v/ADvr/wA46/9+m/P////8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//v78/97l+v8eUu3/ADnr/wA76/8AOuv/EEfs/8vW+f///vz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//f38/+zw+/8xYe7/ADnr/wA76/8AO+v/ADvr/wA76/8A
O+v/ADjr/36b8/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/+/vz/3uX6/x5S7f8AOev/ADvr/wA6
6/8QR+z/y9b5///+/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/9/fz/7PD7/zFh7v8AOev/ADvr
/wA76/8AO+v/ADvr/wA76/8AOOv/fpvz/////P/8/Pz//Pz8//z8/P/8/Pz//Pz8//7+/P/e5fr/
HlLt/wA56/8AO+v/ADrr/xBH7P/L1vn///78//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//39/P/s
8Pv/MWHu/wA56/8AO+v/ADvr/wA76/8AO+v/ADvr/wA46/9+m/P////8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//v78/97l+v8eUu3/ADnr/wA76/8AOuv/EEfs/8vW+f///vz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//f38/+zw+/8xYe7/ADnr/wA76/8AO+v/ADvr/wA76/8AO+v/ADjr/36b8/////z/
/Pz8//z8/P/8/Pz//Pz8//z8/P/+/vz/3uX6/x5S7f8AOev/ADvr/wA66/8PR+z/y9f5/////P//
//z//f38//z8/P/8/Pz//Pz8//z8/P/9/fz/7PD7/zFh7v8AOev/ADvr/wA76/8AO+v/ADvr/wA7
6/8AOOv/fpvz/////P/8/Pz//Pz8//z8/P/8/Pz//Pz8//7+/P/e5fr/HlDt/wA46/8AO+v/ADvr
/wU+6/9SevH/lK31/8PR+P/m6/v/+fr8/////P////z//v38//39/P/s8Pv/MWHu/wA56/8AO+v/
ADvr/wA76/8AO+v/ADvr/wA46/9+m/P////8//z8/P/8/Pz//Pz8//z8/P/8/Pz//f38/+3x+/9r
jfL/HVHt/wI76/8AOOv/ADrr/wA46/8BOuv/DUXs/ytc7v9XfvH/i6X0/7zL+P/i6Pr/+Pn8/+/y
+/8yYe7/ADnr/wA76/8AO+v/ADvr/wA76/8AO+v/ADjr/36b8/////z//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//fz8//n6/P/X4Pr/k6z1/0Rv8P8PR+z/ADnr/wA56/8AOuv/ADnr/wA46/8AOuv/
CkPs/yVX7v9PePD/eJfz/x5S7f8AOuv/ADvr/wA76/8AO+v/ADvr/wA76/8AOOv/fpvz/////P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//7+/P////z/8vT7/8PQ+P93lvP/L1/u/wdA
6/8AOOv/ADrr/wA76/8AO+v/ADnr/wA46/8AOev/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr
/wA36/9+mvP////8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/9/fz/
//78//39/P/m6/v/rL/3/12C8f8cUe3/Ajvr/wA46/8AOuv/ADvr/wA76/8AO+v/ADvr/wA76/8A
Ouv/ADnr/wA46/8FP+v/HlLt/5609v///vz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//39/P////z/+fr8/9bf+f+RqvX/Q2/w/w9G7P8AOev/ADnr
/wA66/8AOOv/ADrr/w5G7P8zYu7/bI7y/6u+9//c5Pr/9/j8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v78/////P/y
9Pv/wtD4/3aW8/8uXu7/HVHt/0p08P+Io/T/w9D4/+vv+//9/fz////8//7+/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//39/P///vz//f38/+br+//b4/r/9ff8/////P///vz//f38//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38//7+/P/9/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAw
AAAAYAAAAAEAIAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAD8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/9/fz///78
//79/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//v78/////P/x9Pv/z9n5/93l+v/4+fz////8///+/P/9/fz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//v38/////P/5+vz/1t/5/5Kq9f9Eb/D/FErs/yJV7f9VfPH/lKz1/8zX
+f/w8/v//v78/////P/+/fz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//f38/////P/9/fz/5Or6/6m89v9bgPH/HFHt/wI76/8A
OOv/ADrr/wA56/8AOOv/ATvr/xNK7P89au//eJfz/7XG9//j6fr/+vv8/////P/+/vz//fz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//7+/P/+/vz/7/L7/77M+P9ykvP/
K1zu/wY/6/8AOOv/ADrr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA66/8AOOv/ADnr/whB7P8o
Wu7/XYLx/5yy9v/S3Pn/8/X7//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//79/P////z/9/j8
/9Da+f+KpfT/Pmrv/w1F7P8AOev/ADnr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/
ADvr/wA76/8AO+v/ADvr/wA76/8AOev/ADjr/wI86/8XTe3/R3Lw/9Da+f///vz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//39
/P////z/+/z8/+Dm+v+htvb/U3vx/xhN7f8BOuv/ADjr/wA66/8AOuv/ADnr/wA46/8AOOv/ADjr
/wE76/8GQOv/CkLs/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AOuv/
BTzr/7TE9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//38/P///vz//v78/+zv+/+3x/f/aYzy/yRX7f8DO+v/ADXq/wA36/8AOOv/ATvr/whB
7P8VS+z/Jlju/z5q7/9Zf/H/d5bz/5au9f+2x/f/hKD0/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr
/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/9/fz//v78//L0+//G0/j/fZvz/zVj7/8LROz/B0Dr/xVL7P8q
W+7/Q27w/1+E8f99m/P/nLL2/7jI9//Q2vn/5On6//H0+//6+/z//v78/////P////3/qb32/wI8
6/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//v7/P/n7Pv/uMj3/3ya8/9cgfH/
Y4fy/4Cd9P+htvb/vcz4/9Te+f/n7Pv/9Pb7//v7/P///vz////8/////P///vz//v38//38/P/8
/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA7
6/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38
/+Tq+v9kiPL/kqv1/9fg+v/3+Pz///78/////P////z////8//7+/P/9/fz//fz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8A
O+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//v78/97l+v8eUe3/CkLs/zxp7/+LpvT/1N75//n6/P////z//f38
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/
p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9///
//z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADnr/wA4
6/8BOuv/HFDt/1+E8f+xwvf/7PD7//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/
ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADrr/wA46/8GP+v/cJDz//v7/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr
/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8A
N+v/VXvx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r
/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/
ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA7
6/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8A
O+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr
/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8A
O+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l
+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/
ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx//r7
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2
/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8A
O+v/ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr
/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA7
6/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/
VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P//
//z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF
9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr
/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8A
O+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/
ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA7
6/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/
BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8e
Uu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr
/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx//r7/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI8
6/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/
ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA7
6/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38
/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8A
O+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/VXzx
//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/
p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9///
//z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA7
6/8AO+v/ADvr/wA76/8AOOv/VXzx//r7/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/
ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8AOOv/Vn3x//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr
/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v38/97l+v8eUu3/ADrr/wA76/8AO+v/ADvr/wA76/8A
OOv/SHLw/+br+//6+/z////8/////P/+/fz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r
/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v78/97l+v8eUO3/
ADnr/wA76/8AO+v/ADvr/wA76/8AO+v/CULs/y5e7v9bgfH/j6n1/7/O+P/k6fr/+Pn8/////P//
//z//v38//z8/P/8/Pz//Pz8//z8/P////z/p7v2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA7
6/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//f38/+fs+/9GcPD/B0Dr/wA46/8AOev/ADvr/wA76/8AO+v/ADvr/wA56/8AOOv/
ATrr/wxE7P8oWu7/U3vx/4ai9P+4yPf/3+X6//b3/P/+/vz////8//7+/P////z/p7v2/wI86/8A
O+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/p7fv/sML3/2GG8v8gU+3/Azzr
/wA46/8AOuv/ADvr/wA76/8AO+v/ADvr/wA66/8AOev/ADjr/wA56/8JQuz/IlXt/0t08P9+m/T/
sML3/9nh+v/3+Pz/qLz2/wI86/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8A
O+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/9/fz////8//r7/P/a4vr/lq71/0dy8P8RSOz/ADnr/wA56/8AO+v/ADvr/wA76/8AO+v/ADvr
/wA76/8AO+v/ADnr/wA46/8AOev/BkDr/x1R7f9FcPD/RnHw/wE86/8AO+v/ADvr/wA76/8AO+v/
ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/+/vz////8//P1+//G0vj/e5nz/zFh
7v8IQOv/ADjr/wA56/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA66/8AOOv/ADnr
/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/BT/r/7TF9/////z/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//38/P///vz//f38/+jt+/+vwff/YIXx/x9T7f8CPOv/ADjr/wA66/8AO+v/ADvr/wA7
6/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr
/wA76/8AOuv/BTzr/7TE9/////z//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//39/P////z/+vr8/9nh+v+V
rfX/R3Hw/xFI7P8AOev/ADnr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA76/8AO+v/ADvr/wA7
6/8AO+v/ADvr/wA76/8AOev/ADjr/wI86/8XTe3/R3Lw/9Da+f///vz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//7+/P////z/8vX7/8XS+P95mPP/MGDu/wdA6/8AOOv/ADrr/wA76/8A
O+v/ADvr/wA76/8AO+v/ADvr/wA66/8AOOv/ADnr/whB7P8oWu7/XYLx/5yy9v/S3Pn/8/X7//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//f38///+/P/9/fz/
5+z7/67A9/9fhPH/HlLt/wI76/8AOOv/ADrr/wA56/8AOOv/ATvr/xNK7P89au//eJfz/7XG9//j
6fr/+vv8/////P/+/vz//fz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//f38/////P/5+vz/2OD6/5Ss9f9GcfD/FErs/yJV7f9VfPH/
lKz1/8zX+f/w8/v//v78/////P/+/fz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//v78
/////P/y9Pv/z9r5/93k+v/4+fz////8///+/P/9/fz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/9/fz///78//79/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz/
/Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8
/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8
/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8//z8/P/8/Pz//Pz8
//z8/P/8/Pz//Pz8//z8/P8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AACJUE5HDQoaCgAAAA1JSERSAAABAAAAAQAIAwAAAGusWFQAAAAzUExURfz8/PnYzfKEX+xHEOs7
APB3T/Snjfnj3O5UIPOQb/fArfWzne5fL/vw7PScfu9rP/jMvb5fRSkAAARJSURBVHja7d0JcqMw
EIVhGQIWixH3P+3gSVJekB0EWlry/w4Qm08vrR6Pq6IUIYQQQgghhBBCZORU1V9Ne079NhLl3Oqv
7+iuT/1m4mdovu5TN8MnFeFa/XXG7pT6jUXJrfrr1NVwSf3+Auep+rYiTOUWwV79dXTVF1iEd9W3
xBR2Pf5dfUsRirket1bfkgKuR8fqW6ZiN6d+hgPZU/11lj0py6l4oPqWIuR2PR6uvqUIGV2Pfqpv
iWkzKILX6q+z7Empn/BdAlTfErEfIwSrvqUI8q7HUxe0+uuI+hjh0o5xn/4nY+oH/04fr/rPSf3o
KkH1RQGkqr4QgITVFwCQtvqpAZJXPy2AgOonBJBR/VQAYqqfBkBQ9RMAyKp+bABx1Y8LILD6EQFk
Vj8WgNjqxwEIXH0jG+Dchfx4z0yzUoIBLkO46tfN74fbYgH6KtTD6+r+k32ZAMGqr6vnDzEFAoSq
/tjZ/l9LHECY6pvp1X/qyQIIUv3/w/5lBAEEqP5t2MsH8F79x2EvHsBv9dfDXjyAv4e3D/sPAXg9
7D8A4P2wLxtgw7AvF2DjsC8TwGHYlwfgOOzLAtgx7MsB2DnsywHw+vQAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAeHkfZvhkgLo7/Ac2cwbwf/g5AQQ5/HwAmjCHnwmAnkIdfhYATR/y6aUDBD586QDBD180
gG7DH75ggGqO8/QyAXTr7e9q5wgQ8fAFAoxRD18aQF2dYj+9JIBxiH74ogCmqpvm+YMBlOqr66+B
qaY+qoMcAKUug/n9maaZhjnK74QkgCXnSd//aGOmdg67EgoDWDJX9fMrjGaa5kBXhDyAJUNjfSFt
AgxKkQDLr0KrX76e30EpFGDJqavfv66fQSkXYEnfbHj5g4NSNMByM7bjxnexd1AKB1hy7rTDm3Ee
lPIB1M+S6JTtgzILgIcl0Sl/D8pMANRqSXRzeD0o8wFQ1iXRKbZBmRWAerkkOuVhUOYG8H5JdMr3
oMwPQG1YEuMmPoDauCSWDOCyJBYKoFyXxAIB1J4lsTCA/UtiMQDq2JJYBIA6viRmD6D8LIl7MqZ+
8Fu8LYmbUzdDpC9ybE3MJVF3c+rHtSbOktjE+g7PnoReEnUV5ftbhxJuSTRtiq8x7EmAJbGu+jTf
YtgZv0viOOVy9PfxtCQu111WR/+Qw0viKPS6c8iBJVH0deeQXUui7uRfdw5xXBJNIUf/kK1Los7s
unPIhiUxz+vOIe+WxLrK+LpziH1JHLvCj/4+z0uivH/Yh89tSSzsunPIdUksZdMhhBBCCCGEEELE
5R9UIX+6hyKbVwAAAABJRU5ErkJggg==')
	#endregion
	$MainForm.Name = 'MainForm'
	$MainForm.StartPosition = 'CenterScreen'
	$MainForm.Text = 'Dynamic Distribution List Members'
	$MainForm.add_Load($MainForm_Load)
	#
	# Disconnectbutton
	#
	$Disconnectbutton.Enabled = $False
	$Disconnectbutton.Location = '94, 33'
	$Disconnectbutton.Name = 'Disconnectbutton'
	$Disconnectbutton.Size = '75, 23'
	$Disconnectbutton.TabIndex = 20
	$Disconnectbutton.Text = 'Disconnect'
	$Disconnectbutton.UseVisualStyleBackColor = $True
	$Disconnectbutton.add_Click($Disconnectbutton_Click)
	#
	# ConnectButton
	#
	$ConnectButton.Location = '13, 33'
	$ConnectButton.Name = 'ConnectButton'
	$ConnectButton.Size = '75, 23'
	$ConnectButton.TabIndex = 19
	$ConnectButton.Text = 'Connect'
	$ConnectButton.UseVisualStyleBackColor = $True
	$ConnectButton.add_Click($ConnectButton_Click)
	#
	# labelPassword
	#
	$labelPassword.AutoSize = $True
	$labelPassword.Location = '184, 38'
	$labelPassword.Name = 'labelPassword'
	$labelPassword.Size = '56, 13'
	$labelPassword.TabIndex = 18
	$labelPassword.Text = 'Password:'
	#
	# PasswordTextBox
	#
	$PasswordTextBox.Anchor = 'Top, Left, Right'
	$PasswordTextBox.Location = '246, 35'
	$PasswordTextBox.Name = 'PasswordTextBox'
	$PasswordTextBox.PasswordChar = '*'
	$PasswordTextBox.Size = '223, 20'
	$PasswordTextBox.TabIndex = 17
	#
	# labelOffice365AdminUserna
	#
	$labelOffice365AdminUserna.AutoSize = $True
	$labelOffice365AdminUserna.Location = '98, 12'
	$labelOffice365AdminUserna.Name = 'labelOffice365AdminUserna'
	$labelOffice365AdminUserna.Size = '142, 13'
	$labelOffice365AdminUserna.TabIndex = 16
	$labelOffice365AdminUserna.Text = 'Office 365 Admin Username:'
	#
	# UserNameTextBox
	#
	$UserNameTextBox.Anchor = 'Top, Left, Right'
	$UserNameTextBox.Location = '246, 9'
	$UserNameTextBox.Name = 'UserNameTextBox'
	$UserNameTextBox.Size = '224, 20'
	$UserNameTextBox.TabIndex = 15
	#
	# ResultGrid
	#
	$ResultGrid.AllowUserToAddRows = $False
	$ResultGrid.AllowUserToDeleteRows = $False
	$ResultGrid.Anchor = 'Top, Bottom, Left, Right'
	$ResultGrid.ColumnHeadersHeightSizeMode = 'AutoSize'
	[void]$ResultGrid.Columns.Add($FirstName)
	[void]$ResultGrid.Columns.Add($LastName)
	[void]$ResultGrid.Columns.Add($Email)
	$ResultGrid.Location = '19, 174'
	$ResultGrid.Name = 'ResultGrid'
	$ResultGrid.ReadOnly = $True
	$ResultGrid.RowHeadersVisible = $False
	$ResultGrid.Size = '445, 264'
	$ResultGrid.TabIndex = 9
	#
	# CurrentStatus
	#
	$CurrentStatus.Location = '0, 509'
	$CurrentStatus.Name = 'CurrentStatus'
	[void]$CurrentStatus.Panels.Add($statusbarpanel1)
	$CurrentStatus.ShowPanels = $True
	$CurrentStatus.Size = '482, 22'
	$CurrentStatus.TabIndex = 8
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($buttonCopyListName)
	$groupbox1.Controls.Add($buttonCopyFilterToClipboar)
	$groupbox1.Controls.Add($buttonShowMembers)
	$groupbox1.Controls.Add($DynamicLists)
	$groupbox1.Controls.Add($buttonRefreshLists)
	$groupbox1.Anchor = 'Top, Left, Right'
	$groupbox1.Location = '13, 66'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '457, 82'
	$groupbox1.TabIndex = 23
	$groupbox1.TabStop = $False
	$groupbox1.Text = 'Dynamic Distribution Group List'
	#
	# buttonCopyListName
	#
	$buttonCopyListName.Anchor = 'Top, Right'
	$buttonCopyListName.Enabled = $False
	$buttonCopyListName.Location = '123, 46'
	$buttonCopyListName.Name = 'buttonCopyListName'
	$buttonCopyListName.Size = '91, 23'
	$buttonCopyListName.TabIndex = 24
	$buttonCopyListName.Text = 'Copy List Name'
	$buttonCopyListName.UseVisualStyleBackColor = $True
	$buttonCopyListName.add_Click($buttonCopyListName_Click)
	#
	# buttonCopyFilterToClipboar
	#
	$buttonCopyFilterToClipboar.Anchor = 'Top, Right'
	$buttonCopyFilterToClipboar.Enabled = $False
	$buttonCopyFilterToClipboar.Location = '220, 46'
	$buttonCopyFilterToClipboar.Name = 'buttonCopyFilterToClipboar'
	$buttonCopyFilterToClipboar.Size = '129, 23'
	$buttonCopyFilterToClipboar.TabIndex = 23
	$buttonCopyFilterToClipboar.Text = 'Copy Filter to Clipboard'
	$buttonCopyFilterToClipboar.UseVisualStyleBackColor = $True
	$buttonCopyFilterToClipboar.add_Click($buttonCopyFilterToClipboar_Click)
	#
	# buttonShowMembers
	#
	$buttonShowMembers.Anchor = 'Top, Right'
	$buttonShowMembers.Enabled = $False
	$buttonShowMembers.Location = '355, 46'
	$buttonShowMembers.Name = 'buttonShowMembers'
	$buttonShowMembers.Size = '95, 23'
	$buttonShowMembers.TabIndex = 22
	$buttonShowMembers.Text = 'Show Members'
	$buttonShowMembers.UseVisualStyleBackColor = $True
	$buttonShowMembers.add_Click($buttonShowMembers_Click)
	#
	# DynamicLists
	#
	$DynamicLists.Anchor = 'Top, Left, Right'
	$DynamicLists.DropDownStyle = 'DropDownList'
	$DynamicLists.Enabled = $False
	$DynamicLists.FormattingEnabled = $True
	$DynamicLists.Location = '6, 19'
	$DynamicLists.Name = 'DynamicLists'
	$DynamicLists.Size = '444, 21'
	$DynamicLists.TabIndex = 5
	$DynamicLists.add_SelectionChangeCommitted($DynamicLists_SelectionChangeCommitted)
	$DynamicLists.add_Click($DynamicLists_Click)
	#
	# buttonRefreshLists
	#
	$buttonRefreshLists.Anchor = 'Top, Right'
	$buttonRefreshLists.Enabled = $False
	$buttonRefreshLists.Location = '21, 46'
	$buttonRefreshLists.Name = 'buttonRefreshLists'
	$buttonRefreshLists.Size = '96, 23'
	$buttonRefreshLists.TabIndex = 21
	$buttonRefreshLists.Text = 'Refresh Lists'
	$buttonRefreshLists.UseVisualStyleBackColor = $True
	$buttonRefreshLists.add_Click($buttonRefreshLists_Click)
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($buttonRefreshMembers)
	$groupbox2.Controls.Add($CopyButton)
	$groupbox2.Controls.Add($Clearbutton)
	$groupbox2.Controls.Add($labelCSVExportFile)
	$groupbox2.Controls.Add($textboxFile)
	$groupbox2.Controls.Add($buttonBrowse)
	$groupbox2.Controls.Add($ExportButton)
	$groupbox2.Anchor = 'Top, Bottom, Left, Right'
	$groupbox2.Location = '12, 154'
	$groupbox2.Name = 'groupbox2'
	$groupbox2.Size = '458, 349'
	$groupbox2.TabIndex = 24
	$groupbox2.TabStop = $False
	$groupbox2.Text = 'Dynamic Distribution Group Members'
	#
	# buttonRefreshMembers
	#
	$buttonRefreshMembers.Anchor = 'Bottom, Right'
	$buttonRefreshMembers.Enabled = $False
	$buttonRefreshMembers.Location = '336, 286'
	$buttonRefreshMembers.Name = 'buttonRefreshMembers'
	$buttonRefreshMembers.Size = '115, 23'
	$buttonRefreshMembers.TabIndex = 22
	$buttonRefreshMembers.Text = 'Refresh Members'
	$buttonRefreshMembers.UseVisualStyleBackColor = $True
	$buttonRefreshMembers.add_Click($buttonRefreshMembers_Click)
	#
	# CopyButton
	#
	$CopyButton.Anchor = 'Bottom, Left'
	$CopyButton.Location = '6, 286'
	$CopyButton.Name = 'CopyButton'
	$CopyButton.Size = '183, 23'
	$CopyButton.TabIndex = 11
	$CopyButton.Text = 'Copy All Members to Clipboard'
	$CopyButton.UseVisualStyleBackColor = $True
	$CopyButton.add_Click($CopyButton_Click)
	#
	# Clearbutton
	#
	$Clearbutton.Anchor = 'Bottom, Right'
	$Clearbutton.Location = '221, 285'
	$Clearbutton.Name = 'Clearbutton'
	$Clearbutton.Size = '109, 24'
	$Clearbutton.TabIndex = 10
	$Clearbutton.Text = 'Clear Results'
	$Clearbutton.UseVisualStyleBackColor = $True
	$Clearbutton.add_Click($Clearbutton_Click)
	#
	# labelCSVExportFile
	#
	$labelCSVExportFile.Anchor = 'Bottom, Left'
	$labelCSVExportFile.AutoSize = $True
	$labelCSVExportFile.Location = '6, 319'
	$labelCSVExportFile.Name = 'labelCSVExportFile'
	$labelCSVExportFile.Size = '83, 13'
	$labelCSVExportFile.TabIndex = 13
	$labelCSVExportFile.Text = 'CSV Export File:'
	#
	# textboxFile
	#
	$textboxFile.Anchor = 'Bottom, Left, Right'
	$textboxFile.AutoCompleteMode = 'SuggestAppend'
	$textboxFile.AutoCompleteSource = 'FileSystem'
	$textboxFile.Location = '97, 316'
	$textboxFile.Name = 'textboxFile'
	$textboxFile.Size = '177, 20'
	$textboxFile.TabIndex = 0
	$textboxFile.add_TextChanged($textboxFile_TextChanged)
	#
	# buttonBrowse
	#
	$buttonBrowse.Anchor = 'Bottom, Right'
	$buttonBrowse.Location = '282, 314'
	$buttonBrowse.Name = 'buttonBrowse'
	$buttonBrowse.Size = '62, 23'
	$buttonBrowse.TabIndex = 1
	$buttonBrowse.Text = 'Browse...'
	$buttonBrowse.UseVisualStyleBackColor = $True
	$buttonBrowse.add_Click($buttonBrowse_Click)
	#
	# ExportButton
	#
	$ExportButton.Anchor = 'Bottom, Right'
	$ExportButton.Enabled = $False
	$ExportButton.Location = '356, 314'
	$ExportButton.Name = 'ExportButton'
	$ExportButton.Size = '96, 23'
	$ExportButton.TabIndex = 12
	$ExportButton.Text = 'Export to CSV'
	$ExportButton.UseVisualStyleBackColor = $True
	$ExportButton.add_Click($ExportButton_Click)
	#
	# SearchLDAP
	#
	$SearchLDAP.Location = '357, 10'
	$SearchLDAP.Name = 'SearchLDAP'
	$SearchLDAP.Size = '104, 24'
	$SearchLDAP.TabIndex = 2
	$SearchLDAP.Text = 'LDAP Search'
	$SearchLDAP.UseVisualStyleBackColor = $True
	#
	# toolbar1
	#
	$toolbar1.DropDownArrows = $True
	$toolbar1.Location = '0, 0'
	$toolbar1.Name = 'toolbar1'
	$toolbar1.ShowToolTips = $True
	$toolbar1.Size = '461, 42'
	$toolbar1.TabIndex = 3
	#
	# statusbarpanel1
	#
	$statusbarpanel1.Alignment = 'Right'
	$statusbarpanel1.AutoSize = 'Spring'
	$statusbarpanel1.BorderStyle = 'Raised'
	$statusbarpanel1.Name = 'statusbarpanel1'
	$statusbarpanel1.Text = 'Disconnected'
	$statusbarpanel1.Width = 465
	#
	# FirstName
	#
	$FirstName.AutoSizeMode = 'AllCells'
	$FirstName.HeaderText = 'First Name'
	$FirstName.Name = 'FirstName'
	$FirstName.ReadOnly = $True
	$FirstName.Width = 82
	#
	# LastName
	#
	$LastName.AutoSizeMode = 'AllCells'
	$LastName.HeaderText = 'Last Name'
	$LastName.Name = 'LastName'
	$LastName.ReadOnly = $True
	$LastName.Width = 83
	#
	# Email
	#
	$Email.AutoSizeMode = 'Fill'
	$Email.HeaderText = 'Email'
	$Email.Name = 'Email'
	$Email.ReadOnly = $True
	#
	# openfiledialog1
	#
	$openfiledialog1.CheckFileExists = $False
	$openfiledialog1.DefaultExt = 'csv'
	$openfiledialog1.Filter = 'CSV File (.csv)|*.csv|All Files|*.*'
	$openfiledialog1.ShowHelp = $True
	$statusbarpanel1.EndInit()
	$groupbox2.ResumeLayout()
	$groupbox1.ResumeLayout()
	$MainForm.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $MainForm.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$MainForm.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$MainForm.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$MainForm.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $MainForm.ShowDialog()

}
#endregion Source: MainForm.psf

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($hostinvocation -ne $null)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	function Connect-O365 {
	    [CmdletBinding()]
	    param ()
	    process {
	        $Params = @{
	            ConfigurationName = 'Microsoft.Exchange'
	            ConnectionUri = 'https://ps.outlook.com/powershell/'
	            Credential = $Global:Credential
	            Authentication = 'Basic'
	            AllowRedirection = $true
	            WarningAction = 'SilentlyContinue'
	            Name = 'O365'
	            ErrorAction = 'Stop'
	        }
	        try {
	            $Global:o365Session = New-PSSession @Params
	            Import-PSSession $Global:o365Session -Prefix 'O365' -AllowClobber -DisableNameChecking -ErrorAction Stop | Out-Null
	        }
	        catch {
	            $Global:o365Session = $Null
	        }
	        
	    }
	    
	}
#endregion Source: Globals.ps1

#Start the application
Main ($CommandLine)
